### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.util'

### ISSUE THREAD

**Issue by jlinkels** [abdeladim-s/subsai#1]
This project looks great.

However, when installing using "pip install git+https://github.com/abdeladim-s/subsai" the installation fails with:
```
ERROR: Could not find a version that satisfies the requirement importlib<1.1.0,>=1.0.4 (from subsai)
ERROR: No matching distribution found for importlib<1.1.0,>=1.0.4

```
I am running Python 3.9.2 on Debian 11 Bullseye. 
As I understand, importlib is  a component of Python 3 and should not have to be installed.
When importing importlib.util in Python this is successful.

```
>>> import importlib.util
>>> 
```
So it seems that the installation fails on the requirement importlib<1.1.0,>=1.0.4. How can I work around this?

Thanks
jlinkels

**Comment by abdeladim-s** [comment]
Thanks @jlinkels.

Yes, you are right, thank you for pointing it out.

I updates the dependencies list, please go ahead and give it another try now ?

**Comment by jlinkels** [comment]
@abdeladim-s  Yes, that solved the issue.
Thanks so much for your quick response.
