### ISSUE TITLE
max_length deprecated

### ISSUE THREAD

**Issue by jooni22** [abdeladim-s/subsai#10]
Hi I have the warning, when run subsai by the command:
`subsai ./Videos/one.mp4 --model openai/whisper --model-configs '{"model_type": "small"}' --format srt --translation-model facebook/mbart-large-50-many-to-many-mmt --translation-source-lang en_XX --translation-target-lang pl_PL`

```
.local/lib/python3.10/site-packages/transformers/generation/utils.py:1288: UserWarning: Using `max_length`'s default (200) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
```
It's only warning. Will you be replacing the max_length parameter with max_new_tokens in the future?

**Comment by abdeladim-s** [comment]
Hi,

I think the warning is comings from the `transformers` library, which `dl-translate` (The library used for translation) depend on, So I hope its maintainers  will soon update their code to fix it. 
If they pushed a new update, I will upgrade `subsai` to use their latest update as well.

Thanks for reporting the issue.
