### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by fouda4ever** [abdeladim-s/subsai#105]
i have windown 10, CPU only
i install the program using
pip install git+https://github.com/abdeladim-s/subsai
i got this

Collecting pywhispercpp==1.1.1 (from subsai==1.2.5)
  Using cached pywhispercpp-1.1.1.tar.gz (230 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dl-translate==0.3.0 (from subsai==1.2.5)
  Using cached dl_translate-0.3.0-py3-none-any.whl.metadata (14 kB)
Collecting faster-whisper==0.10.0 (from subsai==1.2.5)
  Using cached faster-whisper-0.10.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Collecting stable-ts (from subsai==1.2.5)
  Using cached stable-ts-2.14.4.tar.gz (123 kB)
  Preparing metadata (setup.py) ... done
Collecting transformers>=4.30.2 (from dl-translate==0.3.0->subsai==1.2.5)
  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
INFO: pip is looking at multiple versions of dl-translate to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement torch>=2.0.0 (from dl-translate) (from versions: none)
ERROR: No matching distribution found for torch>=2.0.0

when i run subsai-webui
i got this
'subsai-webui' is not recognized as an internal or external command,
operable program or batch file.

**Comment by abdeladim-s** [comment]
What python version are you using ?

**Comment by fouda4ever** [comment]
Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by abdeladim-s** [comment]
seems like there is some conflict between installed packages, Could you please try to create a separate virtual environment for the project ?

**Comment by fouda4ever** [comment]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dl-translate==0.3.0 (from subsai==1.2.5)
  Obtaining dependency information for dl-translate==0.3.0 from https://files.pythonhosted.org/packages/0f/d1/5c56e9806c3bcdb75d6d3d4ab7e966ca328c5fa30bbc53ca54f7151061b7/dl_translate-0.3.0-py3-none-any.whl.metadata
  Downloading dl_translate-0.3.0-py3-none-any.whl.metadata (14 kB)
Collecting faster-whisper==0.10.0 (from subsai==1.2.5)
  Using cached faster-whisper-0.10.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting stable-ts (from subsai==1.2.5)
  Downloading stable-ts-2.14.4.tar.gz (123 kB)
     ---------------------------------------- 123.6/123.6 kB 2.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting transformers>=4.30.2 (from dl-translate==0.3.0->subsai==1.2.5)
  Obtaining dependency information for transformers>=4.30.2 from https://files.pythonhosted.org/packages/20/0a/739426a81f7635b422fbe6cb8d1d99d1235579a6ac8024c13d743efa6847/transformers-4.36.2-py3-none-any.whl.metadata
  Downloading transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
     ---------------------------------------- 126.8/126.8 kB 1.9 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of dl-translate to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.55.2 Requires-Python <3.5
ERROR: Could not find a version that satisfies the requirement torch>=2.0.0 (from dl-translate) (from versions: none)
ERROR: No matching distribution found for torch>=2.0.0

(subsai) F:\HAMO\Languages\Files\Whisper\venv>subsai-webui
'subsai-webui' is not recognized as an internal or external command,
operable program or batch file.

**Comment by abdeladim-s** [comment]
This is weird, I don't know why pip `Could not find a version that satisfies the requirement torch>=2.0.0` even though Pytorch is at version 2.1 now. 
I can think now of two options, either downgrade python to 3.11 and re-try, or better use Docker directly.

**Comment by fouda4ever** [comment]
i am sorry to bother you but i installed docker then

F:\HAMO\Languages\Files\subsai>docker compose run subsai-webui
2024-01-20 22:04:03.993 INFO    matplotlib.font_manager: generated new fontManager
2024-01-20 22:04:11.472 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

  You can now view your Streamlit app in your browser.

  Network URL: http://172.18.0.2:8501
  External URL: http://156.212.53.106:8501



i tried both links  in chrome but it doesn't open "This site can’t be reached"

**Comment by abdeladim-s** [comment]
Can you try: http://localhost:8501/ ?

**Comment by fouda4ever** [comment]
i tried it, but it didn't work.

**Comment by abdeladim-s** [comment]
localhost should work!!
Did you get any errors on the terminal ?

**Comment by fouda4ever** [comment]
no
![cmd_k79r4CdeQE](https://github.com/abdeladim-s/subsai/assets/86977699/ab227f2e-de43-4d02-a903-d150fa6497fe)
![chrome_mWAw9In2R7](https://github.com/abdeladim-s/subsai/assets/86977699/80810e38-6038-4e09-ac99-77ababf4b996)

**Comment by abdeladim-s** [comment]
As long as the docker is running then there is something wrong with your network configuration, 
I wonder if there are any firewall that blocks the connection (as the error says localhost refused to connect)?!
All I can suggest in this case is maybe try a different port or check your network configuration.

**Comment by fouda4ever** [comment]
should i install streamlit or it contained in docker?

**Comment by abdeladim-s** [comment]
Everything is contained in the docker image.

**Comment by fouda4ever** [comment]
it works with
docker compose run -p 8501:8501 subsai-webui
i should specify the port
Thank you

**Comment by abdeladim-s** [comment]
You are welcome.
