### ISSUE TITLE
Select translation language

### ISSUE THREAD

**Issue by AndryOre** [abdeladim-s/subsai#111]
Currently it only automatically translates to English, I would like to be able to select a different translation language.

**Comment by abdeladim-s** [comment]
@AndryOre, the Whisper model supports translation only to English.
If you want to translate to other languages you can use the translation tool included with the project.

**Comment by AndryOre** [comment]
But whisper docs says it is multilingual 😞

**Comment by abdeladim-s** [comment]
Yes, it is multilingual in the sense that it can transcribe different languages but not to translate to another language. 
i.e, transcription supports multi-languages but translation supports only English.

**Comment by abdeladim-s** [comment]
You are welcome :)
