### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bill4bill** [abdeladim-s/subsai#113]
Can seem to get it to install. I get an error. something to do with a file that cant be found. google's gemini ai seems to think its related to something called sentencepiece?

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\>pip install git+https://github.com/abdeladim-s/subsai
Collecting git+https://github.com/abdeladim-s/subsai
 Cloning https://github.com/abdeladim-s/subsai to c:\users\jared\appdata\local\temp\pip-req-build-bs568o8f
 Running command git clone --filter=blob:none --quiet https://github.com/abdeladim-s/subsai 'C:\Users\jared\AppData\Local\Temp\pip-req-build-bs568o8f'
 Resolved https://github.com/abdeladim-s/subsai to commit fb1ceb7ae189269549e60ca53408e144895ba7a0
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting whisper-timestamped@ git+https://github.com/linto-ai/whisper-timestamped (from subsai==1.2.5)
 Cloning https://github.com/linto-ai/whisper-timestamped to c:\users\jared\appdata\local\temp\pip-install-79_nrjil\whisper-timestamped_fa2b01641ca24c17baa3790842263151
 Running command git clone --filter=blob:none --quiet https://github.com/linto-ai/whisper-timestamped 'C:\Users\jared\AppData\Local\Temp\pip-install-79_nrjil\whisper-timestamped_fa2b01641ca24c17baa3790842263151'
 Resolved https://github.com/linto-ai/whisper-timestamped to commit 713626edb4a35f0994fbb2133b97c35ac0df77e6
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting whisperx@ git+https://github.com/m-bain/whisperx.git (from subsai==1.2.5)
 Cloning https://github.com/m-bain/whisperx.git to c:\users\jared\appdata\local\temp\pip-install-79_nrjil\whisperx_3d6852679de54f55bb63bb16eedcd186
 Running command git clone --filter=blob:none --quiet https://github.com/m-bain/whisperx.git 'C:\Users\jared\AppData\Local\Temp\pip-install-79_nrjil\whisperx_3d6852679de54f55bb63bb16eedcd186'
 Resolved https://github.com/m-bain/whisperx.git to commit 8227807fa9e076901ea4b4fbbf79c9777a6f5e03
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting openai-whisper==20231106 (from subsai==1.2.5)
 Using cached openai-whisper-20231106.tar.gz (798 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting streamlit~=1.20.0 (from subsai==1.2.5)
 Using cached streamlit-1.20.0-py2.py3-none-any.whl (9.6 MB)
Collecting streamlit-player~=0.1.5 (from subsai==1.2.5)
 Using cached streamlit_player-0.1.5-py3-none-any.whl (1.7 MB)
Collecting streamlit-aggrid~=0.3.4 (from subsai==1.2.5)
 Using cached streamlit_aggrid-0.3.4.post3-py3-none-any.whl (3.4 MB)
Collecting ffsubsync~=0.4.24 (from subsai==1.2.5)
 Using cached ffsubsync-0.4.25-py2.py3-none-any.whl.metadata (10 kB)
Collecting pandas==1.5.3 (from subsai==1.2.5)
 Using cached pandas-1.5.3.tar.gz (5.2 MB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... done
Collecting pysubs2~=1.6.0 (from subsai==1.2.5)
 Using cached pysubs2-1.6.1-py3-none-any.whl (35 kB)
Collecting pywhispercpp==1.1.1 (from subsai==1.2.5)
 Using cached pywhispercpp-1.1.1.tar.gz (230 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... done
Collecting dl-translate==0.3.0 (from subsai==1.2.5)
 Using cached dl_translate-0.3.0-py3-none-any.whl.metadata (14 kB)
Collecting faster-whisper==0.10.0 (from subsai==1.2.5)
 Using cached faster-whisper-0.10.0.tar.gz (1.5 MB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting stable-ts (from subsai==1.2.5)
 Using cached stable-ts-2.15.6.tar.gz (139 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Collecting transformers>=4.30.2 (from dl-translate==0.3.0->subsai==1.2.5)
 Using cached transformers-4.37.2-py3-none-any.whl.metadata (129 kB)
Collecting torch>=2.0.0 (from dl-translate==0.3.0->subsai==1.2.5)
 Using cached torch-2.2.0-cp312-cp312-win_amd64.whl.metadata (26 kB)
Collecting sentencepiece (from dl-translate==0.3.0->subsai==1.2.5)
 Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... error
 error: subprocess-exited-with-error

 × Getting requirements to build wheel did not run successfully.
 │ exit code: 1
 ╰─> [31 lines of output]
   Traceback (most recent call last):
    File "C:\Users\jared\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
     main()
    File "C:\Users\jared\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
     json_out['return_val'] = hook(**hook_input['kwargs'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jared\scoop\apps\python\current\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
     return hook(config_settings)
         ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jared\AppData\Local\Temp\pip-build-env-v0xdmoeq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
     return self._get_build_requires(config_settings, requirements=['wheel'])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jared\AppData\Local\Temp\pip-build-env-v0xdmoeq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
     self.run_setup()
    File "C:\Users\jared\AppData\Local\Temp\pip-build-env-v0xdmoeq\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
     super().run_setup(setup_script=setup_script)
    File "C:\Users\jared\AppData\Local\Temp\pip-build-env-v0xdmoeq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
     exec(code, locals())
    File "<string>", line 126, in <module>
    File "C:\Users\jared\scoop\apps\python\current\Lib\subprocess.py", line 408, in check_call
     retcode = call(*popenargs, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jared\scoop\apps\python\current\Lib\subprocess.py", line 389, in call
     with Popen(*popenargs, **kwargs) as p:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\jared\scoop\apps\python\current\Lib\subprocess.py", line 1026, in __init__
     self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\jared\scoop\apps\python\current\Lib\subprocess.py", line 1538, in _execute_child
     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   FileNotFoundError: [WinError 2] The system cannot find the file specified
   [end of output]

**Comment by bill4bill** [comment]
after testing it more it seems like it works on the previous release of python but not the current one

**Comment by abdeladim-s** [comment]
@bill4bill, have you installed `ffmpeg` as described in the Readme page ? 
If you are on Windows, you need to run:
```shell
choco install ffmpeg
```
before installing `subsai`.

**Comment by abdeladim-s** [comment]
Ok, sounds good.
Feel free to open another issue should you find any other problem.
