### ISSUE TITLE
Feature Request | Save config

### ISSUE THREAD

**Issue by Kellen-wq** [abdeladim-s/subsai#118]
It would be very convenient to have a system of configs, so that at each restart you don't have to set the necessary parameters manually again. that's why I would like to have a function to be able to create, save and load configs.

**Comment by abdeladim-s** [comment]
@Kellen-wq, 
I had this in mind when I started the project, just didn't find time to make it, actually the CLI already supports loading the configs from a json file.
I've added now an option to export/load the configs in the webui as well.

Give it a try and let me know if you find any issues ?
