### ISSUE TITLE
problem running with nvidea

### ISSUE THREAD

**Issue by diaverso** [abdeladim-s/subsai#121]
I have ubuntu installed on WSL2, with cuda installed.
https://imgur.com/jU0VFJQ

But when I run docker with the command "sudo docker compose run -p 8501:8501 -v /path/to/your/media_files/folder:/media_files subsai-webui" 

I get this error
https://imgur.com/RmA87Wo
How can I solve it?

**Comment by abdeladim-s** [comment]
I think docker does not detect you have a NVIDIA GPU.
Does the nbody docker image run without any problem ?

**Comment by diaverso** [comment]
Yes, it works without any problem.

**Comment by abdeladim-s** [comment]
Have you tried to run the docker with the argument  `--gpus=all` ?
You can take a look at [this example]( https://docs.docker.com/desktop/gpu/)

**Comment by daronyondem** [comment]
> Have you tried to run the docker with the argument `--gpus=all` ? You can take a look at [this example](https://docs.docker.com/desktop/gpu/)

This fixes the issue.
