### ISSUE TITLE
Timestamps issues

### ISSUE THREAD

**Issue by reyaz006** [abdeladim-s/subsai#126]
I'm using faster-whisper and large-v2 to create subtitles for some anime episodes, and it works mostly good. Then I've got this one episode where from the 2:00 mark the next text line gets inserted ahead of the corresponding voice line by about 5 seconds and all the next lines get shifted by too much in the same manner.

Are there any recommended settings I could use to generally avoid mistakes that huge?

**Comment by abdeladim-s** [comment]
The default settings should work generally well for most use cases. If only that one episode didn't work as expected then it is an exception and maybe there is something wrong with it.
Feel free to try other models and play with the settings until you find the ones that work for you.
