### ISSUE TITLE
RuntimeError: This package is a placeholder package

### ISSUE THREAD

**Issue by eni9889** [abdeladim-s/subsai#140]
I am getting the following error when trying to install:

```
  Preparing metadata (setup.py) ... done
  Downloading openai-0.0.2.tar.gz (741 bytes)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q9vgdhs_/openai_e4aa4e8b4ee34b33a7014b0fd097aa42/setup.py", line 6, in <module>
          raise RuntimeError(
      RuntimeError: This package is a placeholder package on the public PyPI instance, and is not the correct version to install. If you are having trouble figuring out the correct package to install, please contact us.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Anyone had similar issues?

**Comment by abdeladim-s** [comment]
@eni9889, I just tested the installation process on Colab and it still  working, so maybe there is something wrong with your system.
I would suggest to create a fresh virtual environment  for the project.

**Comment by eni9889** [comment]
@abdeladim-s I am in windows WSL. I did create a virtual env. I'm now trying it with asdf python version. Will keep you updated

**Comment by eni9889** [comment]
@abdeladim-s tried with python 3.11.0 from asdf and same error. Not sure how to fix at this point

**Comment by abdeladim-s** [comment]
@eni9889,
> @abdeladim-s I am in windows WSL. I did create a virtual env. I'm now trying it with asdf python version. Will keep you updated

Yes WSL is better!


> @abdeladim-s tried with python 3.11.0 from asdf and same error. Not sure how to fix at this point

Please try with Python 3.10 .. Probably a Whisper dependency is not compatible with 3.11 yet.

**Comment by eni9889** [comment]
I was able to fix it by doing 
```
 pip3 install 'langchain[all]'
```

**Comment by abdeladim-s** [comment]
That's weird! The project has nothing to do with `langchain`. 
I don't know what package is depending on it but how did you come with the idea ?

**Comment by eni9889** [comment]
@abdeladim-s I just googled the error I was getting and that was the suggestion. Not sure why

**Comment by abdeladim-s** [comment]
@eni9889, okey no worries! 
Let me know if ou find any other issue.

**Comment by amn-max** [comment]
Works when downgraded from python `3.10.9` to `3.8.9`

**Comment by alexandervlpl** [comment]
Tried `3.8.9` specifically and installed `langchain[all]`, nothing works. Can it be that this openai package needs to be bumped?

**Comment by abdeladim-s** [comment]
@alexandervlpl, I'm still not sure what the cause of this issue is, to be honest.
I am also using Linux and haven't encountered any issues; it's working on Docker as well.
Can you try using Python 3.10?
Also, yes you can bump the OpenAI Whisper package in the requirements.txt file and check if that helps?

**Comment by alexandervlpl** [comment]
Same with the latest 3.10, although building the Docker image did work. Ended up using another solution.
