### ISSUE TITLE
Can't run on windows .. stuck at torchaudio warnings

### ISSUE THREAD

**Issue by alfuraiji** [abdeladim-s/subsai#150]
ok here are the specs so far everything is installed correctly 
1- Python 3.11.0 I made an environment specifically for subai ( also tested without the env and I got the same errors ) and now I'm on 3.10.11 ( because subsai worked with it on Linux server with docker ). However, my windows machine still gives me the same error. 

2- ffmpeg runs correctly when I call it 
3- I did install soundfile + pysoundfile with no luck 

```
(subsai-env) PS C:\pyenvsandbox> subsai-webui
C:\pyenvsandbox\subsai-env\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\pyenvsandbox\subsai-env\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
[02:16:07] INFO     Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]                                                                                                                                                          quirks.py:115
           INFO     Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []                                                                                                                                                   quirks.py:120
C:\pyenvsandbox\subsai-env\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:45: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import (
C:\pyenvsandbox\subsai-env\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
C:\pyenvsandbox\subsai-env\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
```

**Comment by abdeladim-s** [comment]
@alfuraiji, it seems like something is wrong with Pytorch! What version are you using ?

**Comment by alfuraiji** [comment]
the latest 2.5.1 

from here https://pytorch.org/get-started/locally/

**Comment by abdeladim-s** [comment]
so in this case probably downgrade it to 2.0. 
Otherwise, I think, the problem seems related to `pyannote`, update it to the latest version and give it a try. 
```shell
pip install git+https://github.com/pyannote/pyannote-audio
```

**Comment by alfuraiji** [comment]
Ok I think I have a bigger problem than this 
I did update pyannote and I got new message 

but before that I really have a weird issue 

I only can run subsai with py -m .. I can't run it with Python no Py alone .. I have to add py -m 

also running py -m subsai-webui will result in 
"C:\Python310\python.exe: No module named subsai-webui"

running py -m subsai or py -m subsai -h will result in 
" INFO     Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]                                                                                 
   INFO     Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []    "
PS C:\>

this command used to give me the old message of the audio issue but now it only shows this

**Comment by abdeladim-s** [comment]
basically, You should not use python -m to run subsai as it is exposed as an entry script. 
If you installed the venv correctly and activated it, you should be able to run `subsai-webui` without calling python explicitly.

**Comment by alfuraiji** [comment]
I followed the installation guide here ... no mention of making a vnev unless it's automated by your  commands

**Comment by abdeladim-s** [comment]
venv is not necessary, but it's a good practice. 
In your case I would suggest to create a separate venv for the package, to avoid  the issues with your system wide Python installation.

**Comment by alfuraiji** [comment]
Alright .. will do that and let you know .. thanks

**Comment by alfuraiji** [comment]
Ok I did clear all the packages from pip 
then created the venv then go the same audio error then updated the pyannote and then I've got the same latest error 

![image](https://github.com/user-attachments/assets/e482ddb4-6c37-4e15-b897-5db4867b5ec2)

**Comment by abdeladim-s** [comment]
This is wired, everything seems good, there is no error here, those are just INFO messages. 
Basically, when you ran the command, the server of the webui should start. 
Can you try doing the same in WSL, without docker ?

**Comment by alfuraiji** [comment]
All of this since the beginning wasn't in docker but in Windows directly it isn't in WSL it was in windows PowerShell

**Comment by abdeladim-s** [comment]
I meant, instead of using Docker, install it directly inside WSL. 
BTW, why are you using PoweShell ? use the terminal instead!

**Comment by alfuraiji** [comment]
I'm using the Terminal but not WSL .. 
I wan't to have CUDA perfectly running and I thing doing it directly in windows is better 
correct me if I'm wrong .. 
Anyway will try WSL2 right now and see

**Comment by alfuraiji** [comment]
Ok .. after fighting with WSL regarding Python,PiP & VrtualENV .. I managed to get the venv running 
but installing subsai inside it stopped with this error
![image](https://github.com/user-attachments/assets/65ff4552-3409-407d-a3e2-6b748f45cfb8)

I think I will stop tinkering around with running subsai in windows. 
this windows machine have RTX3090 installed which is the reason why I want subsai to be on it 
I can't install Ubuntu for eg on because I need windows to be up and running for other stuff 

my only options here is that I have another computer that have RTX2080ti on it and suffer with the limited memory or wait till I get a better car and put inside my linux server that I have right now .. 

but seriously python and windows is a recipe for a nightmare. 

Thanks for all your help and patience this week 
will keep this ticket open if you a solution for the last problem but if not .. feel free to close it 


Note : for anyone willing to try with windows and keep fighting ... running and installing inside a python virtual environment is way better and have less issues and WSL2 with Ubuntu 22 or above is the only way .. 

if you don't want all of my issues here .. go with a dedicated Linux computer or use docker on Windows
.

**Comment by abdeladim-s** [comment]
Yeah .. a huge nightmare :) 
Don't give up, you are almost there, your previous windows installation was not giving any errors, but it's weird that it does not work either, maybe there is something wrong with your environment! If you want to go a step further you can clone the repository and run the webui file yourself. 

For WSL, it's basically linux, so you should be able to run it (like with docker). The issue you are having is during installation, if you can show me the full logs I might be able to  help. 

Another thing that you might need to try is (probably you are using Python 3.12 or 3.13) use Python 3.11 or 3.10. Some packages seem to be incompatible with the newest versions of Python.

**Comment by alfuraiji** [comment]
I’m actually using 3.10 specifically in all of them .. all of the time
 Because I know since the beginning 3.12 will cause issues

I don’t know how to clone and run .. will search that up

Because running on windows without WSL is my preferred target

**Comment by abdeladim-s** [comment]
Here are the steps;
1- activate the previous venv 
2-
```shell
git clone https://github.com/abdeladim-s/subsai
cd subsai
pip install -r requirements.txt
cd src/subsai
python webui.py
```

**Comment by alfuraiji** [comment]
Ok cloning and running inside the environment  in windows not WSL .. gave me the torchaudio error  and speechbrain info 
Install Pyannote audio fixed the torchadio error and now it gives me the speechbrain info then nothing happens after .. so we basically have the same previous issue 

![image](https://github.com/user-attachments/assets/bcce985a-8502-4032-9542-bc4f48f954ef)

for WSL log files .. shall I upload the full /var/log folder or there is a specific file you need?

**Comment by abdeladim-s** [comment]
in that case, instead of `python webui.py`, can you try `streamlit run webui.py` 

for WSL, just the error you've got during installation. copy/paste here

**Comment by alfuraiji** [comment]
ok streamlit run web.py gave me an ip and port and opened the browser with that page 
and I got the dark theme but blank with Connecting in the corner then it shuts down .. 

I did try cloning also in WSL environment and I got  "ModuleNotFoundError: No module named 'subsai'" also same when using streamlit run I got the same message but in the browser 

![image](https://github.com/user-attachments/assets/84b59ba5-2831-4c7d-9e2c-11d8c7fd6999)

Keep in mind there were no errors in the installations on both windows or WSL

**Comment by alfuraiji** [comment]
Ok I made it work with WSL outside the environment !!! with python webui.py 

the weird thing is it kept showing me there is missing modules and I kept installing them with pip install 

until it asked me for subsai module so I did pip install git+https://github.com/abdeladim-s/subsai

then ran the clone that I cloned inside the env folder with python webui.py and it worked !!! 

yeah now I have a missy installations and duplicates but it worked LOL 

now I have to figure out that windows installation why it's running with not error but with no launch then It shuts down !

**Comment by alfuraiji** [comment]
And now suddenly it runs in WSL with just simply subsai-webui and not with python webui.py
LOL

**Comment by abdeladim-s** [comment]
Glad to hear that it finally works, at least on WSL :)
For the GPU to be available, you need to install cuda as usual. 

For windows, is it just shutting down without any errors ?! it's really weird. Are you running a firewall or something ?!!!
I have no idea to be honest.

**Comment by alfuraiji** [comment]
For the GPU unfortunately CUDA situation with WSL is finicky .. and you can't install Nvidia drivers inside it like regular Ubunto because it only needs to access the Windows one now in my situation is not working and not finding the GPU even when everything is properly installed and set .. so I have to find solution 

Also, I found that WSL sometimes bugs and you don't know that till you restart it 
Even Windows itself with Python having this issue right now Subsai on Windows ( The one outside WSL and outside VENV ) starts to give me the same torch audio error and no matter what I do or install Pyannote it gives me the same torch audio error 

So the situation is a big sign to clear everything and wait until I upgrade my Linux dedicated server.

**Comment by abdeladim-s** [comment]
Yeah, there is an underlying issue with your Windows. Something is wrong!
If you have access to another windows machine maybe you can give it a try there as well .. otherwise Linux is the way to go.

**Comment by alfuraiji** [comment]
Will try to make the CUDA work on WSL because is the only platform that I succeded to run Subsai on .. 
Otherwise will wait till upgrading my linux machine 
My other windows machine is will be slow in performance and can't move cards between both so no need to waste time on it. 

Anyway, thanks so much for all the support in the past few days.

Good Luck

**Comment by abdeladim-s** [comment]
You are welcome :)
WSL is almost there. Just keep trying!

Let me know if you face any other issue.
Good luck!
