### ISSUE TITLE
Only last file from text file is processed

### ISSUE THREAD

**Issue by janot** [abdeladim-s/subsai#16]
on Windows

![Screenshot 2023-03-30 011534](https://user-images.githubusercontent.com/1689966/228688691-57215991-b404-4e16-b98e-677365b9e9a0.png)

**Comment by abdeladim-s** [comment]
@janot, please give it a try now.
Do not forget to update the package to the latest commit.

Let me know if the problem persists.

**Comment by janot** [comment]
It works now, thank you!
