### ISSUE TITLE
wrong,I have this file ,but it can not find

### ISSUE THREAD

**Issue by jsdfhasuh** [abdeladim-s/subsai#20]
![image](https://user-images.githubusercontent.com/49879362/232392145-4c53bae2-c1c5-4216-b986-c2d1d68d59d7.png)
![image](https://user-images.githubusercontent.com/49879362/232392237-79f658b7-5e18-453c-9cf9-4ed484b81a22.png)
![image](https://user-images.githubusercontent.com/49879362/232392355-0c3001fd-772e-4448-9feb-9a443fb66d48.png)

**Comment by abdeladim-s** [comment]
@jsdfhasuh, can you try this : 
`C:\\Users\\dd109\\S01E01.mkv` ?

**Comment by jsdfhasuh** [comment]
it crash but no wrong message

**Comment by jsdfhasuh** [comment]
![image](https://user-images.githubusercontent.com/49879362/232417346-71f14b95-4aac-4e57-a885-e9b4694542c6.png)

**Comment by abdeladim-s** [comment]
@jsdfhasuh sorry, I missed your comments. 
Could you please create a virtual env and reinstall the package on it ?
