### ISSUE TITLE
Incorrect param on WhisperTimeStamped

### ISSUE THREAD

**Issue by juanchosaravia** [abdeladim-s/subsai#33]
Hi! 
First of all, thanks for this awesome lib!! I love it!

I was testing the WhisperTimeStamped model and reading the documentation on the source code I found the option to set the 'segment_type' with these possible values
`'options': ['Sentence', 'Word'],`
![image](https://github.com/abdeladim-s/subsai/assets/5606964/598227a3-a4e3-4fc4-9814-ce1ee458f807)
 
but the code expects lowercase value 'word':
![image](https://github.com/abdeladim-s/subsai/assets/5606964/866c4e6f-5be7-4d10-99eb-2d2eabf2f60c)

So the Options should indicate the value properly or change the code to accept 'Words' 

Took me a while to realize why it was not working.

**Comment by abdeladim-s** [comment]
Hi @juanchosaravia,

You are welcome. Glad you found it useful :) 

Yeah you are right, I think I will just make it small letters in all places. I will fix it quickly. 

Thank you very much for taking the time to debug the code.

**Comment by abdeladim-s** [comment]
@juanchosaravia, Please give it a try now and let me know whether the problem is solved ?

**Comment by juanchosaravia** [comment]
hey that was super quick! thanks!!
Yes looks perfect!

**Comment by abdeladim-s** [comment]
You are welcome :)
