### ISSUE TITLE
Passing a filepath for models

### ISSUE THREAD

**Issue by CopaceticMeatbag** [abdeladim-s/subsai#40]
I'm trying to use the facebook m2m 1.2B model, but python can't download it in time before it times out and crashes the download.  Is it possible to pass a filepath to  a model I've already downloaded? It looks like it's possible in dl-translate, but I'm not sure how I'd access that model_or_path feature via the subsai options.

**Comment by abdeladim-s** [comment]
Hi @CopaceticMeatbag,

I think you can just pass the model path instead of the model name in the [translate](https://abdeladim-s.github.io/subsai/#subsai.main.Tools.translate) method. 

Have you tried this and didn't work ?

**Comment by CopaceticMeatbag** [comment]
Thanks @abdeladim-s - I get an error: `Unable to infer the model_family from "C:/Users/Administrator/m2m100_1.2B/". Try explicitly setting the value of model_family to "mbart50" or "m2m100"`

The code I'm using is as below - I tried several variations on the path string with back/forward slash or raw string etc:

```
import os

from pathlib import Path

import pysubs2

from subsai import Tools

subtitles_file = 'V:\TestAutoSubs.srt'

subs = pysubs2.load(subtitles_file)

translation_model = 'C:/Users/Administrator/m2m100_1.2B/'

source_language = 'English'

target_language = 'Spanish'

format = 'srt'

translated_file = f"{subtitles_file}-{source_language}-{target_language}.{format}"

translated_subs = Tools.translate(subs, source_language=source_language, target_language=target_language, model=translation_model)

translated_subs.save(translated_file)

print(f"translated file saved to {translated_file}")
```

**Comment by abdeladim-s** [comment]
I think you will need to pass a Pytorch model : i.e something that ends with `pth` ! Where did you download the model ? 
from the code above, the `translation_model` var seems to be a folder!

**Comment by CopaceticMeatbag** [comment]
Ah, I thought we had to point to the whole directory! I downloaded from here: https://huggingface.co/facebook/m2m100_1.2B/tree/main

The script tries to download the pytorch_model.bin file (which is where it crashes), I also tried making the `translation_model` point to `C:/Users/Administrator/m2m100_1.2B/pytorch_model.bin` with the same results.

**Comment by abdeladim-s** [comment]
yeah basically it should work with the `pytorch_model.bin` file 
I have checked the `dl-translate` source code as well, and from what I can see you just need the model name or the path to a pretrained model,
In `subsai` I just take the model var and pass it directly to that `TranslationModel` class, so it should be the same!
There is also a [create_translation_model](https://abdeladim-s.github.io/subsai/#subsai.main.Tools.create_translation_model) which returns an instant of that class, you can use it in the `translate` method as well.

**Comment by abdeladim-s** [comment]
oh, so the model_family is not inferred automatically ? Please try the `dl-translate` snippet and let me know if it works ?

**Comment by abdeladim-s** [comment]
@CopaceticMeatbag I have added the `model_family` to the `translate` model, try to reinstall the latest commit and give it a try. Hope it will work now!

**Comment by CopaceticMeatbag** [comment]
You've only gone and bloody done it!! Nice work, all works perfectly :) thank you very much!
