### ISSUE TITLE
Installing on Windows => ModuleNotFoundError: jax requires jaxlib to be installed.

### ISSUE THREAD

**Issue by metheofanis** [abdeladim-s/subsai#41]
I'm trying to install it on Windows.
I've created a new conda environment
```
conda create -n subsai
conda activate subsai
```
Then:
`pip install git+https://github.com/abdeladim-s/subsai`

At the end i try to run it:
`subsai-webui`

I get error:

> ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.

I've checked the installation instructions.
It looks like for windows only CPU is available.
For GPU i read 

> # Note: wheels only available on linux.

Do I miss something?

**Comment by abdeladim-s** [comment]
Yes Jax on windows is still experimental. AFAIK you can use Jax GPU on Windows but it should be thorugh WSL.
If you are on Windows just use WSL in any ways, it is way better. 

But the weird thing is Jax is not part of `subsai` requirements. Could you please copy/paste the full error to check which package is requiring it ? 
Also I suggest to avoid `conda` and use normal `venv` environment.

**Comment by metheofanis** [comment]
Hello,
Thanks for the reply.
Here is the full error:

> Traceback (most recent call last):
>   File "C:\Python39\lib\site-packages\jax\_src\lib\__init__.py", line 25, in <module>
>     import jaxlib as jaxlib
> ModuleNotFoundError: No module named 'jaxlib'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Python39\Scripts\subsai-webui.exe\__main__.py", line 4, in <module>
>   File "C:\Python39\lib\site-packages\subsai\__init__.py", line 1, in <module>
>     from subsai.main import SubsAI, Tools
>   File "C:\Python39\lib\site-packages\subsai\main.py", line 25, in <module>
>     from dl_translate import TranslationModel
>   File "C:\Python39\lib\site-packages\dl_translate\__init__.py", line 3, in <module>
>     from ._translation_model import TranslationModel
>   File "C:\Python39\lib\site-packages\dl_translate\_translation_model.py", line 5, in <module>
>     import transformers
>   File "C:\Python39\lib\site-packages\transformers\__init__.py", line 26, in <module>
>     from . import dependency_versions_check
>   File "C:\Python39\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
>     from .utils.versions import require_version, require_version_core
>   File "C:\Python39\lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
>     from .generic import (
>   File "C:\Python39\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
>     import jax.numpy as jnp
>   File "C:\Python39\lib\site-packages\jax\__init__.py", line 35, in <module>
>     from jax import config as _config_module
>   File "C:\Python39\lib\site-packages\jax\config.py", line 17, in <module>
>     from jax._src.config import config  # noqa: F401
>   File "C:\Python39\lib\site-packages\jax\_src\config.py", line 25, in <module>
>     from jax._src import lib
>   File "C:\Python39\lib\site-packages\jax\_src\lib\__init__.py", line 27, in <module>
>     raise ModuleNotFoundError(
> ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.

**Comment by metheofanis** [comment]
You are right. It's working in WSL!
Thanks.
