### ISSUE TITLE
Subsai Google Colab

### ISSUE THREAD

**Issue by techyescountry** [abdeladim-s/subsai#5]
It showed this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.

then later it showed:

ModuleNotFoundError: No module named 'dl_translate

so i installed dl translate and pywhispercpp but kept having numpy version incompatible? 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

what can i do?

Also, can i run Subsai WebUI in google colab? It showed this error both on Windows and gg colab:

Traceback (most recent call last):
  File "/usr/local/bin/subsai-webui", line 5, in <module>
    from subsai.webui import run
  File "/usr/local/lib/python3.9/dist-packages/subsai/__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "/usr/local/lib/python3.9/dist-packages/subsai/main.py", line 27, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "/usr/local/lib/python3.9/dist-packages/subsai/configs.py", line 11, in <module>
    from subsai.models.whisper_model import WhisperModel
  File "/usr/local/lib/python3.9/dist-packages/subsai/models/whisper_model.py", line 13, in <module>
    import whisper
  File "/usr/local/lib/python3.9/dist-packages/whisper/__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "/usr/local/lib/python3.9/dist-packages/whisper/model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "/usr/local/lib/python3.9/dist-packages/whisper/transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "/usr/local/lib/python3.9/dist-packages/whisper/timing.py", line 7, in <module>
    import numba
  File "/usr/local/lib/python3.9/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.9/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.9/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

Thank you

**Comment by abdeladim-s** [comment]
it seems like a dependency conflict issue.
What OS are you using ? Have you created a virtual environment before the installation  or you are installing it system wide ? 
I will try to update the dependencies on my side as well. 

Regarding colab, I think it might be a way to run the webUI from there, but  I am not quite sure about that! 
But if you want to use the framework just from a Python script, it should be doable from colab.

**Comment by abdeladim-s** [comment]
@techyescountry 
I looks like the new version of whisper is not stable yet.
I made some updates to the dependencies file and I tested the installation in colab, it is  working now. 
you need to install jedi as well `!pip install jedi`
Take a look at the [example notebook ](https://github.com/abdeladim-s/subsai/blob/main/examples/subsai_vad.ipynb)

**Comment by jlinkels** [comment]
I was just preparing to open almost the same issue. Let me add my comments, hopefully it contributes to a solution.

Last week I installed a new Debian machine, running Debian 11.6.0 Bullseye. Python 3.9.2. So this was a pristine installation regarding Python and Poetry.

After cloning subsai, I also run into the error that module dl_translate was missing. @abdeladim-s: I think you have it installed on your computer somehow. It is not in the dependencies, and it is not pulled in by another package.

I added dl_translate to the dependencies in pyproject.toml. But then installation failed because llvmlite 0.34.0 could not be installed.

After googling, somewhere I found that this issue could by solved by adding `numba = "~0.56.0"` to the dependencies. At that did solve this problem.  I had liked to add a link to this solution, but as usual in Google, I find everything which is not the relevant post. Sorry.

Also during running subsai package tiktoken was reported missing. I added `tiktoken = "^0.3.2"` to the dependencies and it was installed without issues.

I was working on [abdeladim-s](https://github.com/abdeladim-s) previous commit and was not able to successfully add the correct dependency for whispercpp. So I commented out the whispercpp model and could run subsai. Note that I only executed the CLI help function to ensure that all dependencies were in order. I did not have a chance anymore to test and actual transcription.

Now [abdeladim-s](https://github.com/abdeladim-s) has committed some new changes in the dependencies which are conlficting with what I did yesterday. So it is no use to create a pull request.

With the knowledge I gained now I will pull in abdeladim-s' latest version and see what happens with the dependencies. Because I have now installed dl-translate and such I might not see any problems anymore. Or I should remove this complete venv and try again from scratch.

**Comment by jlinkels** [comment]
Update @abdeladim-s : I see in your latest commit apparently you changed from `poetry` to pip `setuptools` By the presence of a poetry.lock  file I assumed you were using `poetry` development environment. Apparently that is not true anymore and `pyproject` is now incompatible with `poetry`. That might  obsolete many or all of my comments in the previous post.

**Comment by abdeladim-s** [comment]
thanks @jlinkels for the valuable comments. 

Yes, I replaced `poetry` with `setuptool` because I think `poetry` is just creating an extra unnecessary overhead  in this case. And I pointed `pyproject` dependencies to the `requirements.txt` file, that way, we will have the dependencies in one place.

**Comment by jlinkels** [comment]
> Yes, I replaced `poetry` with `setuptool` because I think `poetry` is just creating an extra unnecessary overhead in this case. And I pointed `pyproject` dependencies to the `requirements.txt` file, that way, we will have the dependencies in one place.

At least I concluded that correctly. Although I have "some" programming experience (starting with Fortran on punch cards) those new programming environments give me quite some headaches. I spent some time to set up a Poetry development environment and to clone this project correctly into it. All tutorials seem to assume one wants to set up a new project, none explain how to use Poetry + existing git repo.

So today I learned how to set up a Python virtual environment and to clone and install this project into it. And I can confirm that installing the virtual environment from the current `requirements.txt` works without any errors.

**Comment by abdeladim-s** [comment]
Programming in `Fortran` is not "some" programming experience, It is a huge programming experience :sweat_smile: 

Yeah I agree, build tools are a real headache, I am surprised you learnt all of that in this short period of time, good job :+1: 

Thanks for the test again. 
Hope it will work on @techyescountry 's end as well.

**Comment by techyescountry** [comment]
> it seems like a dependency conflict issue. What OS are you using ? Have you created a virtual environment before the installation or you are installing it system wide ? I will try to update the dependencies on my side as well.
> 
> Regarding colab, I think it might be a way to run the webUI from there, but I am not quite sure about that! But if you want to use the framework just from a Python script, it should be doable from colab.

im using windows 11 22H2, i installed it system wide. would be awesome if we can run WebUI from colab.

Thank you for updating the dependencies :)

How do you implement dl-translate to translate output srt file from whisper_timestamped model? at word level transcription i thought the srt would be very fractional thus hard to translate accurately

**Comment by techyescountry** [comment]
Hi @abdeladim-s seems like the colab still throw some dependencies conflict 
![image](https://user-images.githubusercontent.com/83461783/226149184-ee60f6bf-55a7-46b1-a6f8-2ea82f1c2313.png)
![image](https://user-images.githubusercontent.com/83461783/226149212-1543fceb-e628-4eac-aa54-116ea8f1fe96.png)
Apparently numba 0.56.4 only support upto numpy 1.24 while pywhispercpp require numpy 1.24.2

**Comment by abdeladim-s** [comment]
> > it seems like a dependency conflict issue. What OS are you using ? Have you created a virtual environment before the installation or you are installing it system wide ? I will try to update the dependencies on my side as well.
> > Regarding colab, I think it might be a way to run the webUI from there, but I am not quite sure about that! But if you want to use the framework just from a Python script, it should be doable from colab.
> 
> im using windows 11 22H2, i installed it system wide. would be awesome if we can run WebUI from colab.
> 
> Thank you for updating the dependencies :)
> 
> How do you implement dl-translate to translate output srt file from whisper_timestamped model? at word level transcription i thought the srt would be very fractional thus hard to translate accurately

Installing the package system wide is not a good idea. 
Please create a new virtual env, so you wont have conflicts with what is already installed on your system. 

`dl-translate` is just a post processing tool, so yeah, applying it on whisper_timestamped will give meaningless translation.

**Comment by techyescountry** [comment]
> > > it seems like a dependency conflict issue. What OS are you using ? Have you created a virtual environment before the installation or you are installing it system wide ? I will try to update the dependencies on my side as well.
> > > Regarding colab, I think it might be a way to run the webUI from there, but I am not quite sure about that! But if you want to use the framework just from a Python script, it should be doable from colab.
> > 
> > 
> > im using windows 11 22H2, i installed it system wide. would be awesome if we can run WebUI from colab.
> > Thank you for updating the dependencies :)
> > How do you implement dl-translate to translate output srt file from whisper_timestamped model? at word level transcription i thought the srt would be very fractional thus hard to translate accurately
> 
> Installing the package system wide is not a good idea. Please create a new virtual env, so you wont have conflicts with what is already installed on your system.
> 
> `dl-translate` is just a post processing tool, so yeah, applying it on whisper_timestamped will give meaningless translation.

Thank you @abdeladim-s for the response. I have been trying the colab notebook but it doesnt seem to work.

How can i make use of dl-translate for subtitle translation then?

**Comment by abdeladim-s** [comment]
> Hi @abdeladim-s seems like the colab still throw some dependencies conflict ![image](https://user-images.githubusercontent.com/83461783/226149184-ee60f6bf-55a7-46b1-a6f8-2ea82f1c2313.png) ![image](https://user-images.githubusercontent.com/83461783/226149212-1543fceb-e628-4eac-aa54-116ea8f1fe96.png) Apparently numba 0.56.4 only supports upto numpy <1.24 while pywhispercpp 1.0.4 requires numpy ~=1.24.2

Have you installed `jedi` as I told you before ? 

Try to re-run the cell. Or restart the runtime. 
I don't think it is a `pywhsipercpp` issue, the problem shows it is a cuda problem.

**Comment by techyescountry** [comment]
Yes i just run the notebook from your github readme.md there's pip install jedi in the first cell

**Comment by abdeladim-s** [comment]
> > > > it seems like a dependency conflict issue. What OS are you using ? Have you created a virtual environment before the installation or you are installing it system wide ? I will try to update the dependencies on my side as well.
> > > > Regarding colab, I think it might be a way to run the webUI from there, but I am not quite sure about that! But if you want to use the framework just from a Python script, it should be doable from colab.
> > > 
> > > 
> > > im using windows 11 22H2, i installed it system wide. would be awesome if we can run WebUI from colab.
> > > Thank you for updating the dependencies :)
> > > How do you implement dl-translate to translate output srt file from whisper_timestamped model? at word level transcription i thought the srt would be very fractional thus hard to translate accurately
> > 
> > 
> > Installing the package system wide is not a good idea. Please create a new virtual env, so you wont have conflicts with what is already installed on your system.
> > `dl-translate` is just a post processing tool, so yeah, applying it on whisper_timestamped will give meaningless translation.
> 
> Thank you @abdeladim-s for the response. I have been trying the colab notebook but it doesnt seem to work.
> 
> How can i make use of dl-translate for subtitle translation then?

You are welcome, I will recheck the colab again.

Use `dl-translate` on normal whisper segments, it will translate the subtitles one by one.

**Comment by techyescountry** [comment]
this one: https://colab.research.google.com/github/abdeladim-s/subsai/blob/main/examples/subsai_vad.ipynb

**Comment by techyescountry** [comment]
> > > > > it seems like a dependency conflict issue. What OS are you using ? Have you created a virtual environment before the installation or you are installing it system wide ? I will try to update the dependencies on my side as well.
> > > > > Regarding colab, I think it might be a way to run the webUI from there, but I am not quite sure about that! But if you want to use the framework just from a Python script, it should be doable from colab.
> > > > 
> > > > 
> > > > im using windows 11 22H2, i installed it system wide. would be awesome if we can run WebUI from colab.
> > > > Thank you for updating the dependencies :)
> > > > How do you implement dl-translate to translate output srt file from whisper_timestamped model? at word level transcription i thought the srt would be very fractional thus hard to translate accurately
> > > 
> > > 
> > > Installing the package system wide is not a good idea. Please create a new virtual env, so you wont have conflicts with what is already installed on your system.
> > > `dl-translate` is just a post processing tool, so yeah, applying it on whisper_timestamped will give meaningless translation.
> > 
> > 
> > Thank you @abdeladim-s for the response. I have been trying the colab notebook but it doesnt seem to work.
> > How can i make use of dl-translate for subtitle translation then?
> 
> You are welcome, I will recheck the colab again.
> 
> Use `dl-translate` on normal whisper segments, it will translate the subtitles one by one.

That's great. I want to write the part to automate translation of whisper SRT file output by implementing dl-translate but i didn't know how to

**Comment by techyescountry** [comment]
If you don't mind can you help me write a few lines of code for translation on colab using dl-translate only? Thank you

**Comment by abdeladim-s** [comment]
> this one: https://colab.research.google.com/github/abdeladim-s/subsai/blob/main/examples/subsai_vad.ipynb

I am updating `pywhispercpp` numpy dependency, I will see if that will fix the problem.

**Comment by abdeladim-s** [comment]
> If you don't mind can you help me write a few lines of code for translation on colab using dl-translate only? Thank you

Sure, you can do that easily with `SubsAI.translate` method. 
I will add an example showcasing that in the examples folder.

**Comment by abdeladim-s** [comment]
> > this one: https://colab.research.google.com/github/abdeladim-s/subsai/blob/main/examples/subsai_vad.ipynb
> 
> I am updating `pywhispercpp` numpy dependency, I will see if that will fix the problem.

Could you please try on end now ?

**Comment by techyescountry** [comment]
@abdeladim-s thank you very much sir, seems like it's working now. It says file not found for the test0.webm but i guess i'll just use yt-dlp and fetch youtube vid later

**Comment by techyescountry** [comment]
> > If you don't mind can you help me write a few lines of code for translation on colab using dl-translate only? Thank you
> 
> Sure, you can do that easily with `SubsAI.translate` method. I will add an example showcasing that in the examples folder.

👍

**Comment by abdeladim-s** [comment]
@techyescountry [Here](https://github.com/abdeladim-s/subsai/blob/main/examples/subsai_translation.ipynb) is an example of how to use `Tools.translate` to translate a subtitles' file. 

Hope it helps.

**Comment by abdeladim-s** [comment]
> @abdeladim-s thank you very much sir, seems like it's working now.

Perfect. 
I will go and close this issue if you don't have any other problems ?

**Comment by techyescountry** [comment]
@abdeladim-s alhamdulillah. Thank you brother seems like it's working. Jazakallah khairan.

**Comment by abdeladim-s** [comment]
> @abdeladim-s alhamdulillah. Thank you brother seems like it's working. Jazakallah khairan.

Waiyak. You are welcome brother :)
