### ISSUE TITLE
hi im using whisperx model. but result not showing speaker diarization.

### ISSUE THREAD

**Issue by bob1o2** [abdeladim-s/subsai#65]

**Comment by abdeladim-s** [comment]
Hi @bob1o2,
have you selected `speaker_labels` in `model configs` and provided your HF_TOKEN and didn't work ?

**Comment by bob1o2** [comment]
Yes. didn't work. I proceeded to export the SRT and all format, which displayed both the timing and the subtitles. don't have speakers id

**Comment by abdeladim-s** [comment]
Could you please reinstall the package and give it a try now ?

**Comment by bob1o2** [comment]
reinstalled but GUI version still not working.

**Comment by abdeladim-s** [comment]
and is it working on the CLI ? 
Also, you need to export the subtitles file to see the speakers! the speakers are not shown on the subs grid on the GUI!
