### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by codeliger** [abdeladim-s/subsai#93]
```
  File "/opt/miniconda3/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
```

Anyone else get this issue?

**Comment by abdeladim-s** [comment]
@codeliger, I think there is something wrong with your Python installation or your SSL certificates are out of date. 
You can try the solutions in this [Stackoverflow thread](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org).

**Comment by codeliger** [comment]
I used the docker container and it solved the issue. I think it was a conda instance of python that was causing the issue.
