### ISSUE TITLE
Support for stable-ts

### ISSUE THREAD

**Issue by kanjieater** [abdeladim-s/subsai#99]
When i was first trying to get WhisperX working I quickly abandoned it because it tended to break too much (can't get it working right now with SubsAI either due to the open issues with it). I moved to https://github.com/jianfch/stable-ts, which has served all of my whisperX needs and more. 

I'm wondering if we could add it to the subsai project?

**Comment by abdeladim-s** [comment]
Thanks @kanjieater for letting me know about `stable-ts`, it seems promising. 
Yes I think we can it to the project. Once I get some free time I will try.

**Comment by abdeladim-s** [comment]
@kanjieater, `stable-ts` is now supported. please give it a try and if there are no issues feel free to close the issue.
